services:
  app:
    build:
      context: .
      dockerfile: docker_prod/php/Dockerfile
    volumes:
      - .:/var/www
      - ./docker_prod/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - app-network

  web:
    build:
      context: .
      dockerfile: docker_prod/nginx/Dockerfile
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
      - ./docker_prod/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - app-network

  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:

volumes:
  dbdata: